# Generated by Django 2.2 on 2021-12-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0003_auto_20211212_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_in_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
