# Generated by Django 2.2 on 2021-12-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0004_book_is_in_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_in_favorites',
        ),
    ]
