# Generated by Django 2.2 on 2021-12-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0005_remove_book_is_in_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_logged_in',
        ),
    ]
