# Generated by Django 2.2 on 2021-12-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0006_remove_user_is_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('quote', models.TextField()),
                ('liked_by', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='app_folder.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
