# Generated by Django 2.2 on 2021-12-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0007_auto_20211217_0211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='FavoriteQuote',
        ),
        migrations.RenameField(
            model_name='favoritequote',
            old_name='by',
            new_name='author',
        ),
    ]
