# Generated by Django 2.2 on 2021-12-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0009_auto_20211217_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritequote',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_quotes', to='app_folder.User'),
        ),
    ]
